services:
  - type: postgres
    name: automationhub-db-new
    plan: free
    ipAllowList: []

  - type: web
    name: automationhub-new
    env: python
    buildCommand: |
      # Install dependencies
      pip install -r requirements.txt
      
      # Create necessary directories
      mkdir -p staticfiles
      mkdir -p media
      
      # Run migrations first
      python manage.py makemigrations
      python manage.py migrate
      
      # Initialize database with data
      python manage.py init_db
      
      # Collect static files
      python manage.py collectstatic --noinput
    startCommand: "gunicorn automationhub.wsgi:application --bind 0.0.0.0:$PORT --log-level debug"
    envVars:
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: automationhub-db-new
          property: connectionString
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_SETTINGS_MODULE
        value: "automationhub.settings"
      - key: DISABLE_COLLECTSTATIC
        value: "1"
    healthCheckPath: /
    autoDeploy: true 