services:
  - type: postgres
    name: automationhub-db
    plan: free
    ipAllowList: []

  - type: web
    name: automationhub
    env: python
    buildCommand: |
      # Install dependencies
      pip install -r requirements.txt
      
      # Create necessary directories
      mkdir -p staticfiles
      mkdir -p media
      
      # Ensure database is ready
      echo "Waiting for database..."
      sleep 10
      
      # Run migrations in order
      echo "Running migrations..."
      python manage.py makemigrations tools --noinput
      python manage.py makemigrations quiz --noinput
      python manage.py migrate tools --noinput
      python manage.py migrate quiz --noinput
      python manage.py migrate --noinput
      
      # Collect static files
      echo "Collecting static files..."
      python manage.py collectstatic --noinput
    startCommand: "gunicorn automationhub.wsgi:application --bind 0.0.0.0:$PORT --log-level debug"
    envVars:
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: automationhub-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_SETTINGS_MODULE
        value: "automationhub.settings"
      - key: DISABLE_COLLECTSTATIC
        value: "1"
    healthCheckPath: /
    autoDeploy: true 