services:
  - type: web
    name: automationhub
    env: python
    buildCommand: |
      chmod +x build.sh
      ./build.sh
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: "gunicorn automationhub.wsgi:application --bind 0.0.0.0:$PORT --log-level debug"
    envVars:
      - key: DEBUG
        value: True
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_SETTINGS_MODULE
        value: "automationhub.settings"
      - key: DISABLE_COLLECTSTATIC
        value: "1"
    autoDeploy: true 