# Generated by Django 5.2.1 on 2025-05-21 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_remove_tool_common_commands_command'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='example',
        ),
        migrations.RemoveField(
            model_name='command',
            name='syntax',
        ),
        migrations.AddField(
            model_name='example',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('javascript', 'JavaScript')], default='python', max_length=20),
        ),
        migrations.CreateModel(
            name='CommandLanguageExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('javascript', 'JavaScript')], max_length=20)),
                ('syntax', models.TextField()),
                ('example', models.TextField(blank=True)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_examples', to='tools.command')),
            ],
            options={
                'ordering': ['language'],
                'unique_together': {('command', 'language')},
            },
        ),
    ]
