# Generated by Django 5.1 on 2025-06-01 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_initial_data'),
        ('tools', '0003_remove_command_example_remove_command_syntax_and_more'),
    ]

    operations = [
    ]
