# Generated by Django 5.1 on 2025-06-01 17:49

from django.db import migrations

def create_initial_categories(apps, schema_editor):
    Category = apps.get_model('tools', 'Category')
    
    # Create initial categories
    categories = [
        {
            'name': 'Web Testing',
            'slug': 'web-testing',
            'description': 'Tools for testing web applications'
        },
        {
            'name': 'API Testing',
            'slug': 'api-testing',
            'description': 'Tools for testing APIs and web services'
        },
        {
            'name': 'Mobile Testing',
            'slug': 'mobile-testing',
            'description': 'Tools for testing mobile applications'
        },
        {
            'name': 'Performance Testing',
            'slug': 'performance-testing',
            'description': 'Tools for performance and load testing'
        }
    ]
    
    for category_data in categories:
        Category.objects.get_or_create(
            slug=category_data['slug'],
            defaults=category_data
        )

def remove_initial_categories(apps, schema_editor):
    Category = apps.get_model('tools', 'Category')
    Category.objects.filter(slug__in=['web-testing', 'api-testing', 'mobile-testing', 'performance-testing']).delete()

class Migration(migrations.Migration):
    dependencies = [
        ('tools', '0005_create_initial_categories'),
    ]

    operations = [
        migrations.RunPython(create_initial_categories, remove_initial_categories),
    ]
